# Generated by Django 3.2.8 on 2021-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('players', models.CharField(max_length=254)),
            ],
        ),
    ]
