# Generated by Django 3.2.8 on 2021-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='players',
            field=models.TextField(),
        ),
    ]
