# Generated by Django 3.2.8 on 2021-11-10 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0002_alter_trial_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='players',
        ),
        migrations.AddField(
            model_name='trial',
            name='selected_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
