# Generated by Django 3.2.8 on 2021-11-10 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_rename_atendee_session_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
