# Generated by Django 3.2.8 on 2021-11-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
